apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: category
  name: category
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: category
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: category
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: RMQ_HOST
              value: amqp://rmq?connection_attempts=5&retry_delay=5
          image: category
          name: category
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
