apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventory
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: inventory
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: RMQ_HOST
              value: amqp://rabbitmq?connection_attempts=5&retry_delay=5
          image: inventory
          name: inventory
          ports:
            - containerPort: 7000
          resources: {}
      restartPolicy: Always
status: {}
