apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pets-store
  name: pets-store
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8000
  selector:
    io.kompose.service: pets-store
status:
  loadBalancer: {}
