apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pets-api
  name: pets-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pets-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: pets-api
    spec:
      containers:
        - env:
            - name: RMQ_HOST
              value: amqp://rmq?connection_attempts=5&retry_delay=5
          image: pets-api
          name: pets-api
          ports:
            - containerPort: 6000
          resources: {}
      restartPolicy: Always
status: {}
